### ISSUE TITLE
Call to function 'onHeartbeat' failed

### ISSUE THREAD

**Issue by Biocef** [Kask29/Domoticz-Renault-Dacia-Plugin#4]
Bonjour,
Depuis 2 jours les données ne remontent plus dans Domoticz, sans que je ne change rien.
Le matin ça fonctionnait et en milieu d'après-midi plus rien.

J'ai pas mal d'erreurs dans les logs : 

> 2024-03-07 10:54:38.886 Error: Dacia: Call to function 'onHeartbeat' failed, exception details:
> 2024-03-07 10:54:38.888 Error: Dacia: Traceback (most recent call last):
> 2024-03-07 10:54:38.888 Error: Dacia: File "/home/pi/domoticz/plugins/Dacia/plugin.py", line 410, in onHeartbeat
> 2024-03-07 10:54:38.888 Error: Dacia: _plugin.onHeartbeat()
> 2024-03-07 10:54:38.888 Error: Dacia: File "/home/pi/domoticz/plugins/Dacia/plugin.py", line 74, in onHeartbeat
> 2024-03-07 10:54:38.888 Error: Dacia: loop.run_until_complete(self.onAction("update"))
> 2024-03-07 10:54:38.888 Error: Dacia: File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
> 2024-03-07 10:54:38.888 Error: Dacia: return future.result()
> 2024-03-07 10:54:38.888 Error: Dacia: File "/home/pi/domoticz/plugins/Dacia/plugin.py", line 204, in onAction
> 2024-03-07 10:54:38.888 Error: Dacia: Location = await vehicle.get_location()
> 2024-03-07 10:54:38.888 Error: Dacia: File "/usr/local/lib/python3.9/dist-packages/renault_api/renault_vehicle.py", line 144, in get_location
> 2024-03-07 10:54:38.888 Error: Dacia: response = await self.session.get_vehicle_data(
> 2024-03-07 10:54:38.888 Error: Dacia: File "/usr/local/lib/python3.9/dist-packages/renault_api/renault_session.py", line 221, in get_vehicle_data
> 2024-03-07 10:54:38.888 Error: Dacia: return await kamereon.get_vehicle_data(
> 2024-03-07 10:54:38.888 Error: Dacia: File "/usr/local/lib/python3.9/dist-packages/renault_api/kamereon/__init__.py", line 307, in get_vehicle_data
> 2024-03-07 10:54:38.888 Error: Dacia: await request(
> 2024-03-07 10:54:38.888 Error: Dacia: File "/usr/local/lib/python3.9/dist-packages/renault_api/kamereon/__init__.py", line 159, in request
> 2024-03-07 10:54:38.888 Error: Dacia: kamereon_response.raise_for_error_code()
> 2024-03-07 10:54:38.888 Error: Dacia: File "/usr/local/lib/python3.9/dist-packages/renault_api/kamereon/models.py", line 135, in raise_for_error_code
> 2024-03-07 10:54:38.888 Error: Dacia: error.raise_for_error_code()
> 2024-03-07 10:54:38.888 Error: Dacia: File "/usr/local/lib/python3.9/dist-packages/renault_api/kamereon/models.py", line 97, in raise_for_error_code
> 2024-03-07 10:54:38.888 Error: Dacia: raise exceptions.KamereonResponseException(
> 2024-03-07 10:54:38.888 Error: Dacia: renault_api.kamereon.exceptions.KamereonResponseException: ('err.func.privacy.on', 'Privacy mode currently ON')

J'ai essayé de comprendre pourquoi mais sans succès, je suis plus à l'aise avec d'autres langages qu'avec le Python.
En lançant un `renault-api status` manuellement, les données remontent correctement...
Merci d'avance pour votre aide.

**Comment by Biocef** [comment]
Bon, j'ai trouvé.
Pour ceux qui auraient des soucis, il faut retirer toutes les lignes faisant référence à la localisation dans plugin.py (rechercher : location, localisation, latitude etc).
Par contre je ne m'explique pas pourquoi ça fonctionnait avant, je veux bien une explication si possible.

**Comment by Kask29** [comment]
Bonjour,
j'ai le même problème, je pense que ca vient de renault-api puisque sur la localisation il renvoi : 
`location: Privacy mode currently ON`

La solution de retirer toutes les lignes de localisation doit donc fonctionner. A l'occasion, dans la configuration du plugin il faudrait ajouter de quoi desactiver certaines fonction qui à priori des fois ne fonctionnent pas.
